import type { APIRoute } from "astro";
import { getCollection } from "astro:content";

/**
 * The Markdown twin of every guide, at the article's own URL plus `index.md`.
 *
 * Served for assistants: handing over clean Markdown removes the step where a
 * model has to work out which parts of a styled page were the article, which
 * is what decides whether it quotes us or something else. Emitted from the
 * same source file the page renders, so the two cannot drift — the previous
 * version was generated by scraping our own HTML and would go stale silently.
 */
export async function getStaticPaths() {
  const posts = await getCollection("blog", ({ data }) => !data.draft);
  return posts.map((post) => ({ params: { slug: post.id }, props: { post } }));
}

export const GET: APIRoute = ({ props }) => {
  const { post } = props as { post: Awaited<ReturnType<typeof getCollection>>[number] };
  const url = `https://campuscli.com/blog/${post.id}/`;
  const { data } = post;

  const header = [
    `# ${data.title}`,
    "",
    `> ${data.description}`,
    "",
    `Fuente: ${url}`,
    // Named only when someone signs it: a first-hand account is worth
    // attributing, and a model quoting it should be able to say who lived it.
    ...(data.author ? [`Autor: ${data.author}`] : []),
    `Actualizado: ${data.updated}`,
    "",
    "---",
    "",
  ];

  if (data.summary?.length) {
    header.push("## En resumen", "");
    // The page renders these as html; strip the tags so the Markdown reads as
    // Markdown rather than as a mix of both.
    for (const line of data.summary) {
      header.push(`- ${line.replace(/<[^>]+>/g, "")}`);
    }
    header.push("");
  }

  // The page draws this as a comparison; here it is written out, because a
  // model reading the guide should get the contrast, not a description of a
  // diagram it cannot see.
  if (data.compare) {
    const { before, after } = data.compare;
    header.push(
      `## ${data.compare.caption ?? "La misma semana, de dos formas"}`,
      "",
      `**${before.title}:** ${before.items.join("; ")}. (${before.cost}.)`,
      "",
      `**${after.title}:** preguntas «${after.question}» y responde: «${after.answer}» (${after.cost}.)`,
      "",
    );
  }

  const faq = data.faq?.length
    ? ["", "## Preguntas frecuentes", "", ...data.faq.flatMap((item) => [`### ${item.q}`, "", item.a, ""])]
    : [];

  // The blank line matters: without it the first paragraph of the body runs
  // into the last bullet above it, and a strict parser reads it as part of
  // that list item instead of as prose.
  const markdown = `${[...header, ""].join("\n")}${post.body?.trim() ?? ""}\n${faq.join("\n")}`.trimEnd();

  return new Response(`${markdown}\n`, {
    headers: {
      // Without an explicit type the file downloads instead of being read, and
      // the site sends X-Content-Type-Options: nosniff, so nothing recovers it.
      "content-type": "text/markdown; charset=utf-8",
    },
  });
};
